name: Docker action with gcr authentication helper
description: Simple extension for the docker/github-actions for able to support default GCR authentication in self-hosted runners.
author: aweris
branding:
  icon: 'anchor'
  color: 'blue'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.cmd }}
inputs:
  cmd:
    description: commands to run( build-push | build | push ).
    required: false
    default: build-push
  registry:
    description: Server address of Docker registry. If not set then will default to Docker Hub
    required: false
    default: eu.gcr.io
  repository:
    description: Docker repository to tag the image with
    required: true
  tags:
    description: Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
    required: false
  tag_with_ref:
    description: Automatically tags the built image with the git reference as per the readme
    required: false
    default: true
  tag_with_sha:
    description: Automatically tags the built image with the git short SHA as per the readme
    required: false
    default: true
  path:
    description: Path to run docker build from
    required: false
    default: "."
  dockerfile:
    description: Name of the Dockerfile (Default is 'path/Dockerfile')
    required: false
  target:
    description: Sets the target stage to build
    required: false
  always_pull:
    description: Always attempt to pull a newer version of the image
    required: false
    default: true
  build_args:
    description: Comma-delimited list of build-time variables
    required: false
  cache_froms:
    description: Comma-delimited list of images to consider as cache sources
    required: false
  labels:
    description: Comma-delimited list of labels to add to the built image
    required: false
  add_git_labels:
    description: Adds labels with git repository information to the built image
    required: false
    default: true
  push:
    description: Whether to push the image
    required: false
    default: true
